services:
  image:
    build: .
    image: yt-dlp-docker:latest

  download-mp3:
    image: yt-dlp-docker:latest
    volumes:
      - ./scripts:/scripts:ro
      - ./source/source.txt:/source/source.txt:ro
      - ./export:/export
    environment:
      - SOURCE_FILE
      - OUTPUT_DIRECTORY
      - AUDIO_FORMAT
      - AUDIO_QUALITY
    command: ./scripts/download-mp3.sh

  download:
    image: yt-dlp-docker:latest
    volumes:
      - ./scripts:/scripts:ro
      - ./source/source.txt:/source/source.txt:ro
      - ./export:/export
    environment:
      - SOURCE_FILE
      - OUTPUT_DIRECTORY
      - MAX_VIDEO_RESOLUTION
      - CONCAT_PLAYLIST
    command: ./scripts/download-video.sh

  split-chapters:
    image: yt-dlp-docker:latest
    volumes:
      - ./scripts:/scripts:ro
      - ./source/source.txt:/source/source.txt:ro
      - ./export:/export
    environment:
      - SOURCE_FILE
      - OUTPUT_DIRECTORY
      - MAX_VIDEO_RESOLUTION
    command: ./scripts/split-chapters.sh
